In [1]:
%pip install yfinance pandas numpy matplotlib

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: yfinance in ./.local/lib/python3.12/site-packages (1.7.0)
Requirement already satisfied: pandas in /opt/conda/lib/python3.12/site-packages (2.3.3)
Requirement already satisfied: numpy in /opt/conda/lib/python3.12/site-packages (2.3.5)
Requirement already satisfied: matplotlib in /opt/conda/lib/python3.12/site-packages (3.10.8)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /opt/conda/lib/python3.12/site-packages (from yfinance) (4.14.3)
Requirement already satisfied: curl_cffi>=0.15 in ./.local/lib/python3.12/site-packages (from yfinance) (0.16.3)
Requirement already satisfied: lxml>=4.9.0 in /opt/conda/lib/python3.12/site-packages (from yfinance) (6.0.2)
Requirement already satisfied: multitasking>=0.0.7 in ./.local/lib/python3.12/site-packages (from yfinance) (0.0.13)
Requirement already satisfied: peewee>=3.16.2 in ./.local/lib/python3.12/site-packages (from yfinance) (4.5.2)
Requirement already satisfied: platformdirs>=2.0.0 in /opt/conda/lib/python3.12/site-packages (from yfinance) (4.5.1)
Requirement already satisfied: protobuf>=3.19.0 in ./.local/lib/python3.12/site-packages (from yfinance) (7.36.2)
Requirement already satisfied: pytz>=2022.5 in /opt/conda/lib/python3.12/site-packages (from yfinance) (2025.2)
Requirement already satisfied: requests>=2.31 in /opt/conda/lib/python3.12/site-packages (from yfinance) (2.32.5)
Requirement already satisfied: websockets>=13.0 in ./.local/lib/python3.12/site-packages (from yfinance) (15.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.12/site-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (12.1.0)
Requirement already satisfied: pyparsing>=3 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: soupsieve>=1.6.1 in /opt/conda/lib/python3.12/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /opt/conda/lib/python3.12/site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in /opt/conda/lib/python3.12/site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /opt/conda/lib/python3.12/site-packages (from curl_cffi>=0.15->yfinance) (2026.1.4)
Requirement already satisfied: pycparser in /opt/conda/lib/python3.12/site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (2.22)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.12/site-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.12/site-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.12/site-packages (from requests>=2.31->yfinance) (2.6.3)
Note: you may need to restart the kernel to use updated packages.

In [2]:
actions= {
     "Schneider Electric": "SU.PA",
    "Prysmian": "PRY.MI",
    "Legrand": "LR.PA",
    "ASML": "ASML.AS",
    "Adyen": "ADYEN.AS",
    "ASM International": "ASM.AS",
    "Nexans": "NEX.PA",
    "Thales": "HO.PA",
    "Dassault Aviation": "AM.PA",
    "Leonardo": "LDO.MI",
    "Technip Energies": "TE.PA",
    "Eramet": "ERA.PA",
    "SPIE": "SPIE.PA"
}

print ("Nombres d'actions:", len(actions))

Nombres d'actions: 13

In [3]:
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
tickers = list(actions.values())

data= yf.download(
    tickers,
    period= "3y",
    auto_adjust= True,
    progress= False
)

prices= data["Close"]
print(prices.shape)
display(prices.head())

(767, 13)

Ticker,ADYEN.AS,AM.PA,ASM.AS,ASML.AS,ERA.PA,HO.PA,LDO.MI,LR.PA,NEX.PA,PRY.MI,SPIE.PA,SU.PA,TE.PA
Date,,,,,,,,,,,,,
2023-10-23,682.200012,175.666550,358.276306,538.922607,58.097397,131.636337,13.195534,76.872719,61.178757,33.465626,23.547089,135.246460,18.823414
2023-10-24,689.000000,179.381851,357.044098,548.675049,59.676647,133.809799,13.407820,76.154984,61.834572,33.282963,22.987774,132.864014,18.583036
2023-10-25,646.200012,180.810822,378.139496,546.822205,58.863094,134.235046,13.562209,76.513855,60.663464,32.533085,23.043705,133.397690,18.851149
2023-10-26,669.200012,181.382385,381.786774,546.724609,59.054520,134.187790,13.557385,75.871674,61.694042,32.485020,22.428463,133.435806,18.712467
2023-10-27,640.000000,177.381317,386.222687,546.334534,59.102375,133.290070,13.364397,76.702736,62.021946,32.475403,22.782694,136.332855,18.675488

In [6]:
print(prices.isna().sum())

Ticker
ADYEN.AS    0
AM.PA       0
ASM.AS      0
ASML.AS     0
ERA.PA      0
HO.PA       0
LDO.MI      6
LR.PA       0
NEX.PA      0
PRY.MI      6
SPIE.PA     0
SU.PA       0
TE.PA       0
dtype: int64

In [7]:
returns = prices.pct_change(fill_method= None)
display(returns.head())

Ticker,ADYEN.AS,AM.PA,ASM.AS,ASML.AS,ERA.PA,HO.PA,LDO.MI,LR.PA,NEX.PA,PRY.MI,SPIE.PA,SU.PA,TE.PA
Date,,,,,,,,,,,,,
2023-10-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-10-24,0.009968,0.021150,-0.003439,0.018096,0.027183,0.016511,0.016088,-0.009337,0.010720,-0.005458,-0.023753,-0.017616,-0.012770
2023-10-25,-0.062119,0.007966,0.059083,-0.003377,-0.013633,0.003178,0.011515,0.004712,-0.018939,-0.022530,0.002433,0.004017,0.014428
2023-10-26,0.035593,0.003161,0.009645,-0.000178,0.003252,-0.000352,-0.000356,-0.008393,0.016988,-0.001477,-0.026699,0.000286,-0.007357
2023-10-27,-0.043634,-0.022059,0.011619,-0.000713,0.000810,-0.006690,-0.014235,0.010954,0.005315,-0.000296,0.015794,0.021711,-0.001976

In [8]:
volatility= returns.std() * np.sqrt(252) * 100
drawdown= (prices / prices.cummax()-1).min() *100

In [9]:
risk_table= pd.DataFrame({
    "Volatilité (%)": volatility,
    "Max Drawdown (%)": drawdown
})

risk_table= risk_table.sort_values("Volatilité (%)")

display(risk_table.round(2))

          Volatilité (%)  Max Drawdown (%)
Ticker
SPIE.PA            25.66            -23.39
LR.PA              27.54            -21.51
AM.PA              29.53            -22.02
HO.PA              29.90            -20.67
SU.PA              31.74            -31.34
TE.PA              31.94            -30.79
NEX.PA             36.03            -42.26
PRY.MI             36.78            -43.54
LDO.MI             37.76            -27.86
ASML.AS            39.83            -44.77
ASM.AS             44.16            -52.05
ADYEN.AS           47.27            -57.46
ERA.PA             48.29            -69.54

In [10]:
#calcule de la corrélation entre chaque paire d'actions
correlation= returns.corr()
display(correlation.round(2))

Ticker,ADYEN.AS,AM.PA,ASM.AS,ASML.AS,ERA.PA,HO.PA,LDO.MI,LR.PA,NEX.PA,PRY.MI,SPIE.PA,SU.PA,TE.PA
Ticker,,,,,,,,,,,,,
ADYEN.AS,1.00,0.07,0.23,0.25,0.14,0.08,0.08,0.28,0.20,0.24,0.21,0.33,0.10
AM.PA,0.07,1.00,0.10,0.12,0.14,0.79,0.67,0.14,0.14,0.16,0.23,0.12,0.17
ASM.AS,0.23,0.10,1.00,0.79,0.29,0.07,0.17,0.51,0.34,0.53,0.25,0.57,0.14
ASML.AS,0.25,0.12,0.79,1.00,0.30,0.08,0.18,0.52,0.37,0.53,0.30,0.57,0.19
ERA.PA,0.14,0.14,0.29,0.30,1.00,0.12,0.13,0.22,0.25,0.26,0.23,0.25,0.17
HO.PA,0.08,0.79,0.07,0.08,0.12,1.00,0.73,0.15,0.10,0.12,0.26,0.11,0.18
LDO.MI,0.08,0.67,0.17,0.18,0.13,0.73,1.00,0.18,0.14,0.19,0.21,0.18,0.23
LR.PA,0.28,0.14,0.51,0.52,0.22,0.15,0.18,1.00,0.54,0.65,0.44,0.72,0.26
NEX.PA,0.20,0.14,0.34,0.37,0.25,0.10,0.14,0.54,1.00,0.63,0.36,0.55,0.18
PRY.MI,0.24,0.16,0.53,0.53,0.26,0.12,0.19,0.65,0.63,1.00,0.39,0.68,0.21
SPIE.PA,0.21,0.23,0.25,0.30,0.23,0.26,0.21,0.44,0.36,0.39,1.00,0.40,0.26
SU.PA,0.33,0.12,0.57,0.57,0.25,0.11,0.18,0.72,0.55,0.68,0.40,1.00,0.25
TE.PA,0.10,0.17,0.14,0.19,0.17,0.18,0.23,0.26,0.18,0.21,0.26,0.25,1.00

In [ ]:
# 1. SPIE et Legrand présentent une volatilité historique relativement faible parmi vos 13 actions.
# 2. Eramet, Adyen et ASM International présentent une volatilité plus élevée et des drawdowns historiques importants.
# 3. Plusieurs entreprises appartiennent à des groupes fortement corrélés, donc il faudra limiter la concentration dans ces groupes.

In [11]:
# les actions historiquement moins volatiles reçoivent un poids plus important
budget= 0.65

inverse_vol= 1/volatility

weights = inverse_vol /inverse_vol.sum() * budget

allocation = pd.DataFrame({
    "Weight (%)" : weights *100,
    "Amount (€)": weights * 200000
})

display(allocation.sort_values("Weight (%)", ascending=False).round(2))

          Weight (%)  Amount (€)
Ticker
SPIE.PA         6.73    13458.10
LR.PA           6.27    12537.51
AM.PA           5.85    11694.18
HO.PA           5.77    11549.33
SU.PA           5.44    10882.00
TE.PA           5.41    10811.33
NEX.PA          4.79     9585.65
PRY.MI          4.70     9390.10
LDO.MI          4.57     9145.51
ASML.AS         4.34     8670.41
ASM.AS          3.91     7819.45
ADYEN.AS        3.65     7305.05
ERA.PA          3.58     7151.38

In [12]:
clean_returns= returns.dropna()
cov_matrix= clean_returns.cov()* 252

display(cov_matrix.round(4))

Ticker,ADYEN.AS,AM.PA,ASM.AS,ASML.AS,ERA.PA,HO.PA,LDO.MI,LR.PA,NEX.PA,PRY.MI,SPIE.PA,SU.PA,TE.PA
Ticker,,,,,,,,,,,,,
ADYEN.AS,0.2217,0.0101,0.0469,0.0449,0.0313,0.0108,0.0140,0.0365,0.0356,0.0412,0.0257,0.0491,0.0150
AM.PA,0.0101,0.0883,0.0122,0.0139,0.0193,0.0705,0.0756,0.0118,0.0148,0.0175,0.0177,0.0112,0.0163
ASM.AS,0.0469,0.0122,0.1955,0.1390,0.0610,0.0093,0.0276,0.0631,0.0545,0.0865,0.0290,0.0807,0.0198
ASML.AS,0.0449,0.0139,0.1390,0.1589,0.0563,0.0096,0.0271,0.0576,0.0542,0.0777,0.0308,0.0734,0.0238
ERA.PA,0.0313,0.0193,0.0610,0.0563,0.2343,0.0168,0.0229,0.0298,0.0438,0.0457,0.0295,0.0391,0.0267
HO.PA,0.0108,0.0705,0.0093,0.0096,0.0168,0.0905,0.0832,0.0123,0.0110,0.0133,0.0201,0.0106,0.0169
LDO.MI,0.0140,0.0756,0.0276,0.0271,0.0229,0.0832,0.1426,0.0189,0.0192,0.0269,0.0202,0.0218,0.0275
LR.PA,0.0365,0.0118,0.0631,0.0576,0.0298,0.0123,0.0189,0.0769,0.0542,0.0661,0.0318,0.0638,0.0231
NEX.PA,0.0356,0.0148,0.0545,0.0542,0.0438,0.0110,0.0192,0.0542,0.1313,0.0841,0.0339,0.0640,0.0215
PRY.MI,0.0412,0.0175,0.0865,0.0777,0.0457,0.0133,0.0269,0.0661,0.0841,0.1353,0.0366,0.0802,0.0254
SPIE.PA,0.0257,0.0177,0.0290,0.0308,0.0295,0.0201,0.0202,0.0318,0.0339,0.0366,0.0667,0.0333,0.0216
SU.PA,0.0491,0.0112,0.0807,0.0734,0.0391,0.0106,0.0218,0.0638,0.0640,0.0802,0.0333,0.1021,0.0258
TE.PA,0.0150,0.0163,0.0198,0.0238,0.0267,0.0169,0.0275,0.0231,0.0215,0.0254,0.0216,0.0258,0.1035

In [13]:
w = weights.reindex(cov_matrix.columns).to_numpy()
portfolio_vol = np.sqrt(w @ cov_matrix.to_numpy() @ w)*100

print(f"Portfolio volatility: {portfolio_vol:.2f}%")

Portfolio volatility: 13.22%

In [14]:
cov = cov_matrix.to_numpy()

high_weight_stocks= weights[weights > 0.05].index

high_mask = cov_matrix.columns.isin(high_weight_stocks)

def portfolio_variance(w):
    return w @ cov @ w

bounds = [
    (0.01, 0.10) if ticker in high_weight_stocks else (0.01, 0.05)
    for ticker in cov_matrix.columns
]

In [15]:
constraints= [
    {
        "type": "eq",
        "fun": lambda w: np.sum(w) - 0.65
    },
    {
        "type": "ineq",
        "fun": lambda w: 0.40 - np.sum(w[high_mask])

    }
]

In [18]:
from scipy.optimize import minimize
result = minimize(
    portfolio_variance,
    x0=w,
    method="SLSQP",
    bounds=bounds,
    constraints=constraints,
    options={"ftol": 1e-12, "maxiter": 500}
)

print(result.success)
print(result.message)

True
Optimization terminated successfully

In [19]:
# Extract optimised portfolio weights
optimal_weights = pd.Series(result.x, index=cov_matrix.columns)

# Calculate optimised portfolio volatility
optimal_vol = np.sqrt(portfolio_variance(result.x)) * 100

print(f"Previous volatility: {portfolio_vol:.2f}%")
print(f"Optimised volatility: {optimal_vol:.2f}%")

# Check portfolio constraints
print(f"Total allocation: {optimal_weights.sum()*100:.2f}%")
print(f"Maximum weight: {optimal_weights.max()*100:.2f}%")
print(f"Weight above 5%: {optimal_weights[optimal_weights > 0.050001].sum()*100:.2f}%")

# Display optimised allocations
display((optimal_weights * 100).sort_values(ascending=False).round(2))

Previous volatility: 13.22%
Optimised volatility: 12.40%
Total allocation: 65.00%
Maximum weight: 10.00%
Weight above 5%: 34.52%

Ticker
TE.PA       10.00
SPIE.PA     10.00
AM.PA        7.99
HO.PA        6.53
ADYEN.AS     5.00
NEX.PA       5.00
LR.PA        4.48
LDO.MI       4.29
ERA.PA       4.04
ASML.AS      3.69
PRY.MI       1.80
ASM.AS       1.18
SU.PA        1.00
dtype: float64

In [20]:
previous_returns = clean_returns @ weights.reindex(clean_returns.columns)
optimised_returns = clean_returns @ optimal_weights.reindex(clean_returns.columns)

previous_sharpe = (
    previous_returns.mean() * 252
    / (previous_returns.std() * np.sqrt(252))
)

optimised_sharpe = (
    optimised_returns.mean() * 252
    / (optimised_returns.std() * np.sqrt(252))
)

print(f"Previous Sharpe: {previous_sharpe:.2f}")
print(f"Optimised Sharpe: {optimised_sharpe:.2f}")

Previous Sharpe: 1.17
Optimised Sharpe: 1.15

In [21]:
mean_returns = clean_returns.mean() * 252

mu = mean_returns.reindex(cov_matrix.columns).to_numpy()
def negative_sharpe(w):
    portfolio_return = w @ mu
    portfolio_risk = np.sqrt(w @ cov @ w)

    return -portfolio_return / portfolio_risk

sharpe_result = minimize(
    negative_sharpe,
    x0=optimal_weights.reindex(cov_matrix.columns).to_numpy(),
    method="SLSQP",
    bounds=bounds,
    constraints=constraints,
    options={"ftol": 1e-12, "maxiter": 500}
)

print(sharpe_result.success)
print(f"Maximum historical Sharpe: {-sharpe_result.fun:.2f}")

True
Maximum historical Sharpe: 1.31

In [22]:
sharpe_weights = pd.Series(
    sharpe_result.x,
    index=cov_matrix.columns
)

# Calculate portfolio volatility
sharpe_vol = np.sqrt(
    sharpe_weights.to_numpy() @ cov @ sharpe_weights.to_numpy()
) * 100

print(f"Portfolio volatility: {sharpe_vol:.2f}%")
print(f"Total allocation: {sharpe_weights.sum()*100:.2f}%")
print(f"Maximum weight: {sharpe_weights.max()*100:.2f}%")
print(f"Weight above 5%: {sharpe_weights[sharpe_weights > 0.050001].sum()*100:.2f}%")

display((sharpe_weights * 100).sort_values(ascending=False).round(2))

Portfolio volatility: 12.82%
Total allocation: 65.00%
Maximum weight: 10.00%
Weight above 5%: 37.32%

Ticker
TE.PA       10.00
SPIE.PA     10.00
HO.PA        9.83
AM.PA        7.49
LDO.MI       5.00
NEX.PA       5.00
PRY.MI       5.00
ASML.AS      5.00
ASM.AS       3.65
ADYEN.AS     1.03
LR.PA        1.00
ERA.PA       1.00
SU.PA        1.00
dtype: float64